CREATE TABLE products (
    id bigint NOT NULL auto_increment,
    UNIQUE_KEY char(20) UNIQUE,
    PRODUCT_TITLE varchar (255),
    PRODUCT_DESCRIPTION text,
    `STYLE#` varchar (255),
    AVAILABLE_SIZES varchar (255),
    BRAND_LOGO_IMAGE varchar (255),
    THUMBNAIL_IMAGE varchar (255),
    COLOR_SWATCH_IMAGE varchar (255),
    PRODUCT_IMAGE varchar (255),
    SPEC_SHEET varchar (255),
    PRICE_TEXT varchar (255),
    SUGGESTED_PRICE char(15),
    CATEGORY_NAME varchar (255),
    SUBCATEGORY_NAME varchar (255),
    COLOR_NAME varchar (255),
    COLOR_SQUARE_IMAGE varchar (255),
    COLOR_PRODUCT_IMAGE varchar (255),
    COLOR_PRODUCT_IMAGE_THUMBNAIL varchar (255),
    SIZE char(15),
    QTY  char(15),
    PIECE_WEIGHT char(15),
    PIECE_PRICE char(15),
    DOZENS_PRICE char(15),
    CASE_PRICE char(15),
    PRICE_GROUP char(15),
    CASE_SIZE char(15),
    INVENTORY_KEY char(15),
    SIZE_INDEX char(15),
    SANMAR_MAINFRAME_COLOR varchar (255),
    MILL varchar (255),
    PRODUCT_STATUS varchar (255),
    COMPANION_STYLES varchar (255),
    MSRP char(15),
    MAP_PRICING char(15),
    FRONT_MODEL_IMAGE_URL varchar (255),
    BACK_MODEL_IMAGE varchar (255),
    FRONT_FLAT_IMAGE varchar (255),
    BACK_FLAT_IMAGE varchar (255),
    PRODUCT_MEASUREMENTS varchar (255),
    PMS_COLOR varchar (255),
    GTIN char(15),
    PRIMARY KEY (id)
);